version: '2.1'

services:
  redis:
    image: redis
    networks:
      - webnet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot

  web:
    image: slack-clone-server
    ports:
      - 8080:8080
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "index.js"]

networks:
  webnet: