version: "3.1"

services:
  redis:
    image: redis
    networks: 
      - webnet

  db:
    image: mysql
    restart: always
    ports:
      - "8999:3306"
    networks:
      - webnet
    environment:
      MYSQL_DATABASE: slack
      MYSQL_ROOT_PASSWORD: admin

  web:
    image: slack-clone-server
    ports:
      - "8080:8080"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "run", "prod"]

networks:
  webnet:
