version: "3.1"

services:
  redis:
    image: redis
    networks: 
      - webnet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "8999:3306"
    networks:
      - webnet
    environment:
      MYSQL_DATABASE: slack
      MYSQL_ROOT_PASSWORD: admin

  web:
    image: andresmontoyain/slack-clone-server:lastest
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      SERVER_URL: http://server-web.com
    volumes:
      - files:/app/files
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "-t", "0", "db:3306", "--", "npm", "run", "prod"]

  nginx:
    image: nginx
    volumes:
      - ./slackserver.template:/etc/nginx/conf.d/slackserver.template
      - files:/files
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "cat /etc/nginx/conf.d/slackserver.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  webnet:

volumes:
  mysqldata:
  files:
